### ISSUE TITLE
Reactivate BIOS control

### ISSUE THREAD

**Issue by cdupont** [ru-ace/dell-fan-monitor#1]
Hi,
I deactivated BIOS control this way:
```
sudo dell-fan-mon -v --bios_disable_method 2 --fan_ctrl_logic_mode 1
```
Just to know, how to reactivate BIOS control now?

**Comment by ru-ace** [comment]
[RTFM](https://github.com/ru-ace/dell-fan-mon/blob/master/readme.md#disable-bios-fan-control):
`On exit (SIGTERM, SIGINT) dell-fan-mon set fans speed to max and try to restore BIOS fan control with corresponding method`

**Comment by cdupont** [comment]
> [RTFM](https://github.com/ru-ace/dell-fan-mon/blob/master/readme.md#disable-bios-fan-control):

I don't think insulting me will solve anything :) 

> `On exit (SIGTERM, SIGINT) dell-fan-mon set fans speed to max and try to restore BIOS fan control with corresponding method`

I know. However, I performed:
```
sudo dell-fan-mon -v --bios_disable_method 2 --fan_ctrl_logic_mode 1
```
And hit CTRL-C. And after that, the behavior of the system changed: the fans went to 0 when idle. Note that I didn't install `dell-fan-mon` as a deamon, I just run the above command to deactivate BIOS control. I currently have `i8kmon` loaded as deamon.

**Comment by ru-ace** [comment]
> I don't think insulting me will solve anything :)

That would be rude if it were not for [my first polite request](https://github.com/vitorafsr/i8kutils/issues/6#issuecomment-461629214) to read manual and find answer for this question :)

> And hit CTRL-C. And after that, the behavior of the system changed: the fans went to 0 when idle. Note that I didn't install `dell-fan-mon` as a deamon, I just run the above command to deactivate BIOS control. I currently have `i8kmon` loaded as deamon.

Look - you ignoring [my answers](https://github.com/vitorafsr/i8kutils/issues/6#issuecomment-461629214):
`1. dell-fan-mon is replacement of i8kmon, so you need to uninstall i8kutils for use it.`
Say another words: dell-fan-mon is not disabling bios tool .... this is my own full replacement of i8kmon "With Blackjack and Hookers" :)
