### ISSUE TITLE
Doesn't work on Dell Precision 5530 with Ubuntu 20.04

### ISSUE THREAD

**Issue by jcwinters** [ru-ace/dell-fan-monitor#10]
When running sudo ./dell-fan-mon -v --bios_disable_method 1 I get the following error

```
Fans autodetect: ƒ0·-1 fans_count = 0
Sensors autodetect: t0·-1 t1·-1 t2·-1 t3·-1
Couldn't autodetect cpu_temp_sensor_id.
```

My sensors -u output
```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 32.000

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 41.000
  temp1_max: 100.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 41.000
  temp2_max: 100.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 41.000
  temp3_max: 100.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 39.000
  temp4_max: 100.000
  temp4_crit: 100.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 40.000
  temp5_max: 100.000
  temp5_crit: 100.000
  temp5_crit_alarm: 0.000
Core 4:
  temp6_input: 40.000
  temp6_max: 100.000
  temp6_crit: 100.000
  temp6_crit_alarm: 0.000
Core 5:
  temp7_input: 40.000
  temp7_max: 100.000
  temp7_crit: 100.000
  temp7_crit_alarm: 0.000

BAT0-acpi-0
Adapter: ACPI interface
in0:
  in0_input: 12.653
curr1:
  curr1_input: 0.001

dell_smm-virtual-0
Adapter: Virtual device
fan1:
  fan1_input: 2491.000
fan2:
  fan2_input: 2491.000
```

**Comment by ru-ace** [comment]
Hi! Seems your dell smm bios doesn't inform about temp sensors and fans types.
For example this is my output of `sensors -u`
```
dell_smm-virtual-0
Adapter: Virtual device
Processor Fan:
  fan1_input: 0.000
Processor Fan:
  fan2_input: 0.000
CPU:
  temp1_input: 51.000
GPU:
  temp2_input: 49.000
SODIMM:
  temp3_input: 59.000
```
You can try use i8kctl from https://github.com/vitorafsr/i8kutils to control fans state from command line
Sorry, but it seems that dell-fan-mon cannot be used on your device.

**Comment by Yamakuzure** [comment]
@jcwinters : I had the same problem on my new Dell Precision 7550 with Gentoo Linux.

I had to activate the following kernel options, the modules then got autoloaded on next start:

````
CONFIG_DELL_SMBIOS=m
CONFIG_DELL_SMBIOS_WMI=y
CONFIG_DELL_SMBIOS_SMM=y
CONFIG_I8K=m
CONFIG_SENSORS_DELL_SMM=m
````

In the configuration file I have:
```
mode                0
bios_disable_method 2
discrete_gpu_mode   2
get_gpu_temp_cmd    nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader
gpu_fan_id          1
fans_count          2
````

I think I will raise the thresholds a bit, because 45° for "low" is rarely reached unless the laptop is idle for a longer time.

**Comment by Edenharder** [comment]
> @jcwinters : I had the same problem on my new Dell Precision 7550 with Gentoo Linux.
> 
> I had to activate the following kernel options, the modules then got autoloaded on next start:
> 
> ```
> CONFIG_DELL_SMBIOS=m
> CONFIG_DELL_SMBIOS_WMI=y
> CONFIG_DELL_SMBIOS_SMM=y
> CONFIG_I8K=m
> CONFIG_SENSORS_DELL_SMM=m
> ```
> 
> In the configuration file I have:
> 
> ```
> mode                0
> bios_disable_method 2
> discrete_gpu_mode   2
> get_gpu_temp_cmd    nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader
> gpu_fan_id          1
> fans_count          2
> ```
> 
> I think I will raise the thresholds a bit, because 45° for "low" is rarely reached unless the laptop is idle for a longer time.

Could you share more information about how to activate those kernel options? Is it possible to configure that in grub?
