### ISSUE TITLE
Operation not permitted problem

### ISSUE THREAD

**Issue by robmro27** [ru-ace/dell-fan-monitor#2]
Hi, I appreciate your effort of provide this package, unfortunately I'am not able to run it. 
Please forgive if this is some kind of simple but I can't get it to work, can you help me ?

```
robert@robert-G5-5590:~/Downloads/dell-fan-mon$ sudo ./dell-fan-mon --mode 1 --fan_ctrl_logic_mode 1 --bios_disable_method 2
init_ioperm: Operation not permitted

robert@robert-G5-5590:~/Downloads/dell-fan-mon$ sudo ./dell-fan-mon --mode 0 --fan_ctrl_logic_mode 1 --bios_disable_method 2
discrete_gpu_mode = 1 required mode = 1 (direct SMM BIOS calls) for autodetect and get GPU temp
You can set get_gpu_temp_cmd in /etc/dell-fan-mon.conf for providfing command to get gpu temp. This allow you to use mode = 0.

robert@robert-G5-5590:~/Downloads/dell-fan-mon$ sudo make test
./dell-fan-mon --test
init_ioperm: Operation not permitted
make: *** [Makefile:23: test] Error 1

```

My fans are still working with --mode 0, even if temp is about 49C so they should be off.
The same behavior I noticed while try to use i8kmon, config table define fans to off, but they always has speed  "1"

**Comment by ru-ace** [comment]
Hi! 
About `init_ioperm: Operation not permitted` - it's very strange behavior. Could you provide me `uname -a`, name of linux distributive  and it version, notebook model. Fast search in google says cause maybe  in "enabled secure boot" in bios. 

About second one, please try:
```
./dell-fan-mon -v --mode 0 --fan_ctrl_logic_mode 1 --bios_disable_method 0 --discrete_gpu_mode 0
```

**Comment by robmro27** [comment]
```Linux robert-G5-5590 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

```robert@robert-G5-5590:~/Downloads/dell-fan-mon$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

```Dell Inspiron G5 i7-9750H GTX1650```

Ok your second hint to run with GPU actually start work, but I found a bug unfortunately, I will start a new issue, because it's not related.

After switch off secure boot in bios something has changed. It not throw permission denied error now, but it actually stays no reporting anything to output, is this ok ?

**Comment by ru-ace** [comment]
> After switch off secure boot in bios something has changed. It not throw permission denied error now, but it actually stays no reporting anything to output, is this ok 

Yes - it's ok. Use `-v` to monitoring (but be sure that there no dell-fan-mon daemons was running (if you `make install`)
