### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by neruben** [ru-ace/dell-fan-monitor#5]
clarence@ImperialStarDestroyer:~$ cd dell-fan-mon
clarence@ImperialStarDestroyer:~/dell-fan-mon$ sudo make install
[sudo] password for clarence: 
if test -f "/etc/systemd/system/dell-fan-mon.service" || test -f "/etc/init.d/dell-fan-mon"; then /usr/sbin/service dell-fan-mon stop; fi
install -m0755 dell-fan-mon /usr/bin
install: omitting directory 'dell-fan-mon'
Makefile:26: recipe for target 'install' failed
make: *** [install] Error 1
clarence@ImperialStarDestroyer:~/dell-fan-mon$ 

I get this message , something I can do?

**Comment by ru-ace** [comment]
Hi. 
1. Can you tell me your distro-name and it version?
2. Have you followed the instructions in the installation section at the end of the manual? In other words: did you run `make` before `make install`?

**Comment by neruben** [comment]
clarence@ImperialStarDestroyer:~$ cd dell-fan-mon
clarence@ImperialStarDestroyer:~/dell-fan-mon$ make
cc -g -O2 -Wformat -Werror=format-security -Wall dell-fan-mon.c -o dell-fan-mon
make: cc: Command not found
Makefile:17: recipe for target 'dell-fan-mon' failed
make: *** [dell-fan-mon] Error 127
clarence@ImperialStarDestroyer:~/dell-fan-mon$ sudo make test
[sudo] password for clarence: 
./dell-fan-mon --test
make: ./dell-fan-mon: Command not found
Makefile:23: recipe for target 'test' failed
make: *** [test] Error 127
clarence@ImperialStarDestroyer:~/dell-fan-mon$ sudo make install
if test -f "/etc/systemd/system/dell-fan-mon.service" || test -f "/etc/init.d/dell-fan-mon"; then /usr/sbin/service dell-fan-mon stop; fi
install -m0755 dell-fan-mon /usr/bin
install: cannot stat 'dell-fan-mon': No such file or directory
Makefile:26: recipe for target 'install' failed
make: *** [install] Error 1
clarence@ImperialStarDestroyer:~/dell-fan-mon$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by ru-ace** [comment]
[how to compile program from source in ubuntu 18.04](https://www.google.com/search?newwindow=1&ei=6y2bXY7qG43mrgTAs6uADg&q=how+to+compile+program+from+source+in+ubuntu+18.04&oq=how+to+compile+program+from+source+in+ubuntu+18.04&gs_l=psy-ab.3...5418.5671..5751...0.0..0.89.227.3......0....1..gws-wiz.......33i10.oDGrNnMJqTw&ved=0ahUKEwjOi7jLkYrlAhUNs4sKHcDZCuAQ4dUDCAs&uact=5)
