### ISSUE TITLE
Dell Latitude 7300 (2019)

### ISSUE THREAD

**Issue by dd23** [ru-ace/dell-fan-monitor#8]
I'm trying to run dell-fan-mon on a recent Latitude 7300 (2019 model), but I can't get it to detect the sensors or fans on Arch linux `Linux arch7300 5.4.15-arch1-1`

Does dell-fan-mon require any specific kernel modules or other services?

Here are some outputs:
```
sudo ./dell-fan-mon -v
dell-fan-mon v1.2.2 by https://github.com/ru-ace
Fan monitor and control for Dell laptops via direct SMM BIOS calls or dell-smm-hwmon(i8k) kernel module.

Fans autodetect: ƒ0·-1 fans_count = 0
Sensors autodetect: t0·-1 t1·-1 t2·-1 t3·-1
Couldn't autodetect cpu_temp_sensor_id.
```

For comparison `sensors` works so far.
```
sensors -u
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 54.000
  temp1_max: 100.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 52.000
  temp2_max: 100.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 53.000
  temp3_max: 100.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 53.000
  temp4_max: 100.000
  temp4_crit: 100.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 54.000
  temp5_max: 100.000
  temp5_crit: 100.000
  temp5_crit_alarm: 0.000

dell_smm-virtual-0
Adapter: Virtual device
fan1:
  fan1_input: 0.000

pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 51.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 25.000
  temp1_crit: 107.000

iwlwifi-virtual-0
Adapter: Virtual device
temp1:
ERROR: Can't get value of subfeature temp1_input: Can't read

BAT0-acpi-0
Adapter: ACPI interface
in0:
  in0_input: 8.359
curr1:
  curr1_input: 0.001
```

Let me know if you need more information. Thanks!

**Comment by ru-ace** [comment]
Hi!
> Does dell-fan-mon require any specific kernel modules or other services?

By default - no. 
```
dell_smm-virtual-0
Adapter: Virtual device
fan1:
  fan1_input: 0.000
```
Seems kernel module couldn't detect fans and sensors too. 

The only thing I can advise is to disable secure boot in bios, if it enabled.
But I have doubts that this will help. Seems Dell changed the addresses of the SMM functions that are used to detect fans and sensors.

**Comment by dd23** [comment]
At that point the fan was actually off, but sensors does detect it correctly. At least it shows a number when I can hear the fan: 
```
dell_smm-virtual-0
Adapter: Virtual device
fan1:
  fan1_input: 4383.000
```

**Comment by ru-ace** [comment]
My mistake, but anyway - sensors not detected. So dell-fan-mon couldn't work.
To be sure, could you try i8kctl from https://github.com/vitorafsr/i8kutils to control fan state?

**Comment by dd23** [comment]
I will give i8kctl a try. Thanks for the hint.

Let me know if I can be of any help here, e.g., if you want figure out sensor detection on the 7300 or so.

**Comment by ru-ace** [comment]
Sorry, but I am not a kernel developer and cannot help you with sensor detection.
I created this project only because I have a Dell laptop and one day (after updating the BIOS) it start keep fans always on. I examined existing solutions - and no one suits me, so I decided to create my own with using some code from kernel and other related projects (see credits section).
