### ISSUE TITLE
Jump period not working

### ISSUE THREAD

**Issue by DmitriyMurzin** [ru-ace/dell-fan-monitor#9]
My laptop Dell 7250 with intel i7-5600 CPU

Config:
```
  mode                  smm
  discrete_gpu_mode     cpu integrated
  fan_ctrl_logic_mode   default
  bios_disable_method   2
  period                1000 ms
  jump_timeout          5000 ms
  jump_temp_delta       40°
  t_low  / t_low_fan    55° / off
  t_mid  / t_mid_fan    65° / low
  t_high / t_high_fan   90° / high
  cpu_temp_sensor_id    0 (autodetected)
```

Monitor:
`61·0   61·0   91·0   ƒ0=2   64·2   62·2   62·2`

See `91·0   ƒ0=2   64·2`
In period 1s
Jump period 5s
Temp delta 40c...

Why?

**Comment by ru-ace** [comment]
Hi!
91-61 = 30 
delta = 40 
30 < 40 - so its not abnormal jump.
set delta = 10, and then if temps difference between measuring will be more or equal 10c, it will work.

**Comment by DmitriyMurzin** [comment]
Thanks) it works!
